flask_webapp/main/routes.py
from flask import render_template, request, Blueprint
from flask_webapp.models import Post
from flask_webapp.dashapp import dash_app

main = Blueprint('main', __name__)


# dummy data
posts = [
	# {	
	# 'author' : 'Eirik Selander',
	# 'title' : 'Blog Post 1',
	# 'content' : 'First post content',
	# 'date_posted' : 'April 20, 2018'
	# }
]


# route decorator (a way to add functionality to the function)
# devides how/where to access the specific page
@main.route('/') # the default page
@main.route('/home')
def home():
	# the content of the route is in a render_template html file which we create
	return render_template('home.html', posts=posts)

@main.route('/screener')
def screener():
	return render_template('screener.html', dash_url=dash_app.url_base, title='Stock Screener')

@main.route('/factor_invest')
def factor_invest():
	return render_template('factor_invest.html', title='Factor Investing Wiki')

@main.route('/machine_learning_wiki')
def machine_learning_wiki():
	return render_template('machine_learning_wiki.html', title='Machine Learning Wiki')
 
@main.route('/backtester')
def backtester():
	return render_template('backtester.html', title='Backtesting')
 

flask_webapp/users/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect, request
from flask_webapp import db, bcrypt
from flask_webapp.users.forms import RegistrationForm, LoginForm, UpdateAccountForm
from flask_webapp.models import User, Post
from flask_login import login_user, current_user, logout_user, login_required
from flask_webapp.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm)
from flask_webapp.users.utils import save_picture

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = RegistrationForm()
	# checks if form was validated on submit
	if form.validate_on_submit():
		# storing user details from forms.py
		# hashing the pw
		hashed_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		user = User(username=form.username.data, email=form.email.data, password=hashed_pw)

		# add the created user to the db
		db.session.add(user)
		db.session.commit()
		flash('Account created successfully.', 'success')
		return redirect(url_for('users.login'))

		# give message / alert
		flash(f"Account created for {form.username.data}.",'success')
		return redirect(url_for('main.home'))
	return render_template('register.html', 
		title='Register', form = form)


@users.route('/login', methods=['GET', 'POST'])
def login():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = LoginForm()
	if form.validate_on_submit():  
		# check what username (email) was entered during the singin
		user = User.query.filter_by(email=form.email.data).first()

		# if it exists
		if user and bcrypt.check_password_hash(user.password, form.password.data):
			# use the login_user function and enter the user from above
			login_user(user, remember=form.remember.data)
			# redirecting the user to the page they were trying to access after signing in
			next_page = request.args.get('next')

			# if successful, redirect to home
			return redirect(next_page) if next_page else redirect(url_for('main.home'))
		else:
			flash('Sign in failed. Please check details again.','danger')

	return render_template('login.html', 
		title='Sign In', form = form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
	form = UpdateAccountForm()
	if form.validate_on_submit():
		# profile picture upload
		if form.pic.data:
			pic_file = save_picture(form.pic.data)
			current_user.image_file = pic_file
		current_user.username = form.username.data
		current_user.email = form.email.data
		# commit the changes in our DB
		db.session.commit()
		flash('Account updated.', 'success')
		return redirect(url_for('users.account'))
	elif request.method == 'GET':
		form.username.data = current_user.username
		form.email.data = current_user.email


	image_file = url_for('static',
		filename='profile_pics/'+current_user.image_file) 
	return render_template('account.html', title='Account',
		image_file = image_file, form=form)

flask_webapp/templates/account.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
	  <div class="media">
	    <img class="rounded-circle account-img" src="{{ image_file }}">
	    <div class="media-body">
	      <h2 class="account-heading">{{ current_user.username }}</h2>
	      <p class="text-secondary">{{ current_user.email }}</p>
	    </div>
	  </div>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Change Account Details</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.pic.label() }}
                    {{ form.pic(class="form-control-file") }}
                    {% if form.pic.errors %}
                            {% for error in form.pic.errors %}
                                <span class="text-danger" >{{ error }}</span></br>
                            {% endfor %}
                    {% endif %}

                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
	</div>
{% endblock content %}

flask_webapp/templates/backtester.html
<!-- Backtester Page Template -->
{% extends "layout.html" %}
{% block content %}
    <h1>Backtester App</h1>
    <body>
    	Contains another dash webapp for factor investing and backtesting.


    </body>
{% endblock content %}

flask_webapp/templates/factor_invest.html
<!-- Factor Investing Page Template -->
{% extends "layout.html" %}
{% block content %}
    <h1>Factor Investing Wiki</h1>
    <body>
		<!--This allows us to have latex math notation-->
    	<script type="text/x-mathjax-config">
		MathJax.Hub.Config({
		  TeX: {
		     equationNumbers: {  autoNumber: "AMS"  },
		     extensions: ["AMSmath.js", "AMSsymbols.js", "autobold.js", "color.js"]
		  }
		});
		</script>

		<script type="text/javascript"
		 src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
		</script>

		<!-- Start article here: -->
		<p>
			An asset pricing factor (hereafter referred to as factors) is any characteristic or property that can explain the cross-sectional differences in the returns of assets (Blitz and Vidojevic, 2019). Researchers try to identify factors which are persistent over time and have strong predictive power over a large range of assets (Miller, 2006). A factor strategy is an investment strategy where the investor exploits market anomalies which potentially outperform the overall market. Additionally, the investor might construct multi-factor portfolios by combining factors to take advantage of the low correlation between the different factor portfolios. This can give the investor a higher degree of diversification. Factor strategies are consequently synonymous with alternative risk premia. A market anomaly is a situation where securities behave contrary to the Efficient Market Hypothesis (EMH). The diversification effect can be seen in the picture below, where we notice that strategies such as Value and Minimum Volatility do well in consecutive years, indicating that certain factor portfolios have low correlation. As a result of their dynamic nature, it can prove valuable for investors and researchers to test and rank the different factors at different points in time. 
		</p>
		<!-- Factor overview picture -->
		<p>
			<img src="/static/profile_pics/factor_overview.jpg" width = '100%', height = '5%'>
			 <center> Source: JP Morgan Factor Performance, "Guide to the Markets". </center>
		</p>
		<p>	
			The ground-breaking work by Sharpe (1964) separated overall market risk ß from the idiosyncratic risk of individual stocks. This literature, along with Modern Portfolio Theory, was key in identifying the different sources of return (market versus idiosyncratic).  Later, Fama and French (1993) identified two additional such sources of cross-sectional stock return, namely size (“SMB”) and value (“HML”). These sources of returns, also known as factors, seek to explain the cross-sectional differences in returns between stocks. Researchers try to identify factors which are persistent over time and have strong predictive power over a large range of stocks (Miller 2006). Let us now look closer at some of the most commonly used asset pricing factors.

		</p>
		<b>Value</b>
		<p>
		</p>
		<b>Size</b>
		<p>
		</p>
		<b>Momentum</b>
		<p>		

		</p>
		<p>
			While the use of quantitative strategies such as factor strategies has its roots in academia, it has slowly made its way into the financial services industry, most notably among quantitative hedge funds (funds that employ algorithmic trading and Machine Learning). One of the largest firms in this sector, Two Sigma, has seen its assets under management grow from around $6 billion in 2011 to over $50 billion in 2017 (Wigglesworth, 2018). Furthermore, 5 out of the top 6 hedge funds in Institutional Investors 2018 hedge fund rankings were quantitative funds. Machine Learning is also growing in other parts of financial services like robo-advisory, underwriting, and credit-scoring.

		</p>






		This web page visualizes the function \(
		u(t) = Ae^{-bt}\sin (w t), \hbox{ for } t\in [0,T]
		\).
    </body>
{% endblock content %}

flask_webapp/templates/home.html
{% extends "layout.html" %}
{% block content %}
    {% for post in posts %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="#">{{ post.author }}</a>
              <small class="text-muted">{{ post.date_posted }}</small>
            </div>
            <h2><a class="article-title" href="#">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
{% endblock content %}

flask_webapp/templates/layout.html
<!DOCTYPE html>
<html>
<head>

    <!-- Browser FavIcon -->
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">    

    {% if title %}
        <title>Factor Strategies  - {{ title }}</title>
    {% else %}
        <title>Factor Strategies </title>
    {% endif %}
    
</head>
	<body>
		<header class="site-header">
		  <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
		    <div class="container">
		      <a class="navbar-brand mr-4" href="/">
				<!-- Navbar logo here -->
			    <img src="https://www.flaticon.com/premium-icon/icons/svg/2207/2207146.svg" width="30" height="30" class="d-inline-block align-top" alt="">
			    Factor Strategies
			  </a>

		      </a>
		      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
		        <span class="navbar-toggler-icon"></span>
		      </button>
		      <div class="collapse navbar-collapse" id="navbarToggle">
		        <div class="navbar-nav mr-auto">

		          <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>

		          <a class="nav-item nav-link" href="{{ url_for('main.screener') }}">Stock Screener</a>

		          <a class="nav-item nav-link" href="{{ url_for('main.factor_invest') }}">Factor Investing Wiki</a>

		          <a class="nav-item nav-link" href="{{ url_for('main.machine_learning_wiki') }}">Machine Learning Wiki</a>

  		          <a class="nav-item nav-link" href="{{ url_for('main.backtester') }}">Backtesting</a>


		        </div>
		        <!-- Navbar Right Side -->
		        <div class="navbar-nav">
		        	{% if current_user.is_authenticated %}
      			        <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
      			        <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Sign Out</a>
		        	{% else %}
			          <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Sign In</a>
			          <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
			        {% endif %}
		        </div>
		      </div>
		    </div>
		  </nav>
		</header>

	<main role="main" class="container">
	  <div class="row">
	    <div class="col-md-8">
	    	{% with messages = get_flashed_messages(with_categories=true) %}
	    	{% if messages %}
	    		{% for category, message in messages %}
	    		<div class="alert alert-{{ category }}">
	    			{{ message }}
	    		</div>
	    		{% endfor %}
	    	{% endif %}
	    	{% endwith %}

	      {% block content %}{% endblock %}
	    </div>

	    <!-- Sidebar (deleted for now) -->
<!-- 	    <div class="col-md-4">
	      <div class="content-section">

	        <h3>Sidebar</h3>
	        <p class='text-muted'>Put information here. Maybe if I can have it uniquely for each page.
	          <ul class="list-group">
	            <li class="list-group-item list-group-item-light">Value Factor</li>
	            <li class="list-group-item list-group-item-light">Momentum Factor</li>
	            <li class="list-group-item list-group-item-light">Volatility Factor</li>
	          </ul>
	        </p>
	      </div>
	    </div>
	  </div> -->
	</main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>



</body>
</html>

flask_webapp/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Sign In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                    
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <<small class="text-muted ml-2">
                <a href="#">Forgot Password?</a>
            </small>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Don't have an account? <a class="ml-2" href="{{ url_for('users.login') }}">Register Here.</a>
        </small>
    </div>
{% endblock content %}

flask_webapp/templates/machine_learning_wiki.html
<!-- Factor Investing Page Template -->
{% extends "layout.html" %}
{% block content %}
    <h1>Machine Learning Wiki</h1>
    <img src="/static/profile_pics/matrix2.jpg", width="100%", height="5%">

    <body>
    	<script type="text/x-mathjax-config">
		MathJax.Hub.Config({
		  TeX: {
		     equationNumbers: {  autoNumber: "AMS"  },
		     extensions: ["AMSmath.js", "AMSsymbols.js", "autobold.js", "color.js"]
		  }
		});
		</script>


		<!-- Start article here: -->
		<p>
		<script type="text/javascript"
		 src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
		</script>

		<H4>Introduction</H4>

		Machine Learning (ML) can be defined as the application of set of high-dimensional models for statistical prediction (Marsland, 2014). The <i>learning</i> refers to the fact that the algorithms adapt and modify their actions using information from the data - rather than explicit instructions - to improve their accuracy. In contrast to traditional econometrics, Machine Learning is about estimating a function \( f(\cdot) \)
		to predict an outcome \(y\), rather than estimating the parameter associated with the predictor. In other words, ML estimates \(\hat{y}\), while econometrics estimates \(\hat{\beta}\). Consequently, Machine Learning allows us to test a more extensive list of possible variables and richer functional forms than traditional empirical methods used in asset pricing. In this paper I concentrate on regression models, as we predict stock returns (a continuous variable), rather than classification which predicts categories (e.g. whether a stock is "outperforming" or "underperforming"). We will now look at some topics in depth, starting with parameters.
		</p>

		<H4>Parameters</H4>
		<p>
			Parameters are variables that are internal to the model and their value can be estimated from the data. They are thus not typically set by the researcher. An example is the β-coefficients of a linear regression. Hyperparameters are external to the model and their value cannot be estimated from the data (James et al., 2013). For instance, the number of trees in a random forest. These parameters need to be set manually to maximise the model’s out of sample performance. Next we will look at some machine learning models in detail.
		</p>

		<H4>Linear Regression</H4>
		<p>
			Suppose we are looking to predict the excess returns from some stock market data. Let the vector of predictor variables be given as \(X\) and the outcome variable excess returns as \(y\). My data then consists of \(n\) pairs of the two: \( (x_1, y_1), ..., (x_n, y_n) \). The relationship between \(X\) and \(y\) is given as: $$y=X\beta + \varepsilon$$ where $$\mathbf{E} [\varepsilon |X]=0, $$ also known as the strict exogeneity assumption, this implies that our estimator variables are independent of the error term, i.e. not correlated. Further, we assume that $$Var(\varepsilon |X)=\sigma^2, $$ where \(\sigma \) is a constant, so we assume constant variance of the error term. The random error term allows the relationship between \(y\) and \(X\) to have a non-deterministic component (Berk and Devore, 2012). We want to estimate the true value of \( \beta \) from a sample using Ordinary Least Squares (OLS). This is done by solving the following minimisation problem: $$ \min_{\beta} ||y-X\beta||^2  $$. The objective function above is also called the Residual Sum of Squares (RSS). The solution to the problem yields the OLS estimator $$\hat{\beta}_{OLS} = (X^TX)^{-1}(X^TY),$$ which is the value of $\beta$ that minimises the RSS. See figure below for an illustration.
		</p>
		<p>
			<img src="/static/profile_pics/ols_opt.png", class="center">
		</p>

		<H4>Bias-Variance Tradeoff</H4>
		<p>
			One typically considers two characteristics of a model's estimators: bias and variance. Bias is defined as the difference between the true population parameter \(\beta \) and the expected estimator from the sample: $$\text{Bias}(\beta_{\text{OLS}}) = \mathbf{E}(\beta_{\text{OLS}}) - \beta.$$  One can think of the bias as the \textit{inaccuracy} of our estimate. Variance on the other hand, measures the uncertainty or spread of our estimate (Berk and Devore, 2012), and is given as: $$\text{Var}(\beta_{\text{OLS}}) = (X^TX)^{-1} \sigma_e^2.$$ If \(\ k \) is the number of predictor variables, we can estimate the variance of residuals (\(\ \hat{\sigma}_e^2 \)), which is the variation around the fitted regression line, as
			 $$     \hat{\sigma}_e^2 = \frac{1}{n-k-1}\sum_{i=1}^N(y_i - \hat{y_i})^2 $$

			where \(\ n \) is the number of observations. Note that we divide by \(\ n-k-1 \) rather than \(\ n \) to make \(\ \hat{\sigma}_e^2 \) an unbiased estimate of \(\ E(\hat{\sigma}_e^2)=\hat{\sigma}_e^2 \). Bias and variance are two sources of prediction error and we (ideally) want to minimise both. In practice we need to find a balance between the two. Let the model's total prediction error (Err) be given as: $$\text{Err} = E(Y-\hat{y})^2$$
			$$= \left[E(X\hat{\beta})-X\beta\right]^2 +
			E\left(X\hat{\beta}-E[X\beta]\right)^2 +\sigma_e^2$$
			$$ = \text{Bias}^2+\text{Variance}+\sigma^{2}_{e}.$$

			So, total prediction error consists of error from bias and variance, and an irreducible error (from the noise term) which would still occur even with infinite data regardless of model. While the OLS estimator is the Best Linear Unbiased Estimator (BLUE by the Gauss-Markow Theorem), it can have high variance when the number of predictor variables gets high and particularly if they are highly correlated. This can be seen from Equation above, when the number of variables \(\ k \) approaches the number of observations \(\ n \), the variance goes to infinity. This is the main problem with using OLS on large financial datasets with accounting data, price data and so on. Similarly, in the plot below, we see that when the number of variables (here noted as "Model Complexity") increases, we achieve lower bias, but higher variance. Since OLS estimator is unbiased, we can improve the model by increasing the bias slightly, which reduces the variance and the total prediction error. This process is called regularisation (Gu, Kelly, and Xiu, 2019).
			
			<img src="http://scott.fortmann-roe.com/docs/docs/BiasVariance/biasvariance.png" class="center"> 

			In situation above, we want to reduce the number of variables k until we reach the optimal model complexity, in which we have minimal prediction error.
		</p>


		<H4>Elastic Net</H4>
		<p>
			Suppose you want to predict stock returns using a set of predictor variables like price to earnings ratio, EPS, firm size, or price series like momentum and volatility. If our varaible set is large, and possibly correlated, it could be beneficial to penalise or "shrink" certain parameter estimates. Elastic net combines the penalties of ridge and LASSO into a convex combination of the two. The following loss function is minimised:

			$$\label{elasticnet}
			    \min_{\beta} ||y-X\beta||^2 + \lambda(\alpha ||\beta||^2 + (1-\alpha)||\beta||)
			$$ 

			where \(\ \lambda \geq 0 \) is the hyperparemeter which controls the amount of shrinkage. Larger \(\ \lambda \) means more shrinkage of the coefficients, which are shrunk towards zero, meaning we impose a size-constraint on the coefficients (Taylor, 2018). Notice that when \(\ \lambda \rightarrow 0 \), we approach the OLS objective function. Inside the penalty term we have first the absolute penalty (which is known as l1 regularisation), which is the ridge regression-part. The second is the squared penalty (l2 regularisation), which represents the LASSO-part. The main difference between l1 and l2 is that l2 shrinks all the coefficients to a non-zero value, while l1 shrinks some of the coefficients all the way to zero, completely removing certain variables (Taylor, 2018). The hyperparameter \(\ \alpha\) decides the relative weight of l and l2. If \(\ \alpha = 1\), we are fitting a LASSO regression, and vice versa. One would use hyperparameter tuning to find the optimal value for \(\ \alpha\).
		</p>

		<H4>Decision Tree</H4>
		<p>
			The decision tree regression (or "regression tree") is a non-parametric model, meaning it does not make any assumptions about the data and its distribution (in contrast with linear regression and elastic net which are parametric), instead it makes assumptions about the hyperparameters of the algorithm. The regression tree breaks down the dataset into smaller and smaller subsets at various split points. The tree chooses a region \(\ R \) to split the data such that it minimises the within region squared error around the mean (Townshend, 2018). It solves the following minimisation problem:
			$$
			    \min_{\{R_m\}_{m=1}^M} \frac{1}{N_m}\sum_{i\in R_m}(y_i - \bar{y}_m)^2
			$$

			To optimise our in-sample fit (and overfit our model) one would choose a region for each data point. However, this would quickly lead to a "NP hard" problem, which means there will be too many combinations to solve (Hastie, Tibshirani, and Friedman, 2017). Also, the model would perform poorly out of sample. The solution is to search only on hypercurves, which can be found using recursive binary splits (Townshend, 2018). As an example, in the figure below, I have fitted a regression tree on a US stock dataset with only 1 variable (1-month price momentum). The top part shows recursive binary splits. The bottom part shows how the regression tree is fitted on the data. Each discrete jump corresponds to the depth of the tree. Increasing the tree depth will increase the in-sample fit but also the chance of overfitting if set too high).

			<img src="/static/profile_pics/dtr_sp1.png" class='center'>

			At each decision node, the model decides how to split the data into sub-samples. At the terminal node, we end up with a region \(\ R_i \). Decision Trees are greedy algorithms,  which means they are designed to guarantee finding a solution (but not necessarily the most optimal one). The predicted variable (e.g. stock return) \(\ \hat{y} \) is found as the mean of \(\ y \) in each region. Looking across the splits on the terminal nodes in the figure above, we notice how values of stock returns increase for higher momentum values. This is also evident in the graph. The size of the tree is one of the hyperparameters we tune, as it controls the complexity and overfitting trade-off highlighted previously. For example, if we tune the tree depth to a very high value, the blue line would try to reach all the individual red observations, and overfit. The goal is rather to fit as many as it need to maximise the out of sample prediction accuracy. The remaining models we will look at are variations of the decision tree.
		</p>

		<H4>Bagging</H4>











    </body>
{% endblock content %}

flask_webapp/templates/screener.html
<!-- Screener Page Template -->
{% extends "layout.html" %}
{% block content %}
    <h1>Stock Screener</h1>
    <body>
    	
    	
        <div style="width: 100%; min-height:800px;" >
			<iframe 
			  noresize='noresize' 
			  style='position: absolute; background: transparent; width: 95%; height:100%;' 
			  src={{ dash_url }}
			  frameborder="0">
			</iframe>
        </div>


    </body>
{% endblock content %}